name: Build efd-go
on:
  push:
    branches:
      - main
      - master
      - azure
  pull_request:
    branches:
      - main
      - master
      - azure
  workflow_dispatch:
env:
  ARTIFACT_ID: efd-go
  VERSION: 1.0.0
  GROUP_ID: com.example
jobs:
  build:
    name: Go Build
    if: "vars.ACTIVE_CLOUD == 'azure'"
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
      - name: Log in to Azure
        uses: azure/login@v2
        with:
          creds: "${{ secrets.AZURE_CREDENTIALS }}"
      - name: Log in to Azure Container Registry
        uses: docker/login-action@v3
        with:
          registry: "${{ secrets.ACR_LOGIN_SERVER }}"
          username: "${{ secrets.ACR_USERNAME }}"
          password: "${{ secrets.ACR_PASSWORD }}"
      - name: Build and push Docker image
        env:
          ACR_LOGIN_SERVER: "${{ secrets.ACR_LOGIN_SERVER }}"
          ACR_REPOSITORY: efd-go
        run: |
          SHORT_SHA=${GITHUB_SHA::8}
          docker build -t $ACR_LOGIN_SERVER/$ACR_REPOSITORY:latest -t $ACR_LOGIN_SERVER/$ACR_REPOSITORY:$SHORT_SHA -t $ACR_LOGIN_SERVER/$ACR_REPOSITORY:${{ github.run_number }} -t $ACR_LOGIN_SERVER/$ACR_REPOSITORY:${{ github.sha }} .
          docker push $ACR_LOGIN_SERVER/$ACR_REPOSITORY:latest
          docker push $ACR_LOGIN_SERVER/$ACR_REPOSITORY:$SHORT_SHA
          docker push $ACR_LOGIN_SERVER/$ACR_REPOSITORY:${{ github.run_number }}
          docker push $ACR_LOGIN_SERVER/$ACR_REPOSITORY:${{ github.sha }}
  deploy:
    name: Deploy to Azure Container Apps
    if: "vars.ACTIVE_CLOUD == 'azure'"
    needs: build
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
      - name: Log in to Azure
        uses: azure/login@v2
        with:
          creds: "${{ secrets.AZURE_CREDENTIALS }}"
      - name: Deploy new image to Container App
        run: |
          az containerapp update \
            --name "efd-go-uat-app" \
            --resource-group "efd-go-uat-rg" \
            --image "${{ secrets.ACR_LOGIN_SERVER }}/efd-go:${{ github.sha }}"
